[tool.poetry]
name = "sep-groupb"
version = "0.1.0"
readme = "README.md"
authors = [
    "Malik Durmus <malikdurmus2@gmail.com>"
]
description = "Reinforcement Learning from Human Feedback Framework"
packages = [
    { include = "rlhf"}
]


[tool.poetry.dependencies]
python = ">=3.9,<3.11"
tensorboard = "^2.10.0"
wandb = "^0.13.11"
gym = "0.23.1"
torch = ">=1.12.1"
stable-baselines3 = "2.0.0"
gymnasium = ">=0.28.1"
moviepy = "^1.0.3"
pygame = "2.1.0"
rich = "<12.0"
tenacity = "^8.2.2"
tyro = "^0.5.10"
mujoco = "<=2.3.3"
numpy = ">=1.21.6"
flask = "^3.1.0"
flask-cors = "^5.0.0"

ale-py = { version = "0.8.1", optional = true }
AutoROM = { extras = ["accept-rom-license"], version = "~0.4.2", optional = true }
opencv-python = { version = "^4.6.0.66", optional = true }
procgen = { version = "^0.10.7", optional = true }
pytest = { version = "^7.1.3", optional = true }
imageio = { version = "^2.14.1", optional = true }
openrlbenchmark = { version = "^0.1.1b4", optional = true }
jax = { version = "0.4.8", optional = true }
jaxlib = { version = "0.4.7", optional = true }
flax = { version = "0.6.8", optional = true }
optuna = { version = "^3.0.1", optional = true }
optuna-dashboard = { version = "^0.7.2", optional = true }
envpool = { version = "^0.6.4", optional = true }
PettingZoo = { version = "1.18.1", optional = true }
SuperSuit = { version = "3.4.0", optional = true }
multi-agent-ale-py = { version = "0.1.11", optional = true }
shimmy = { version = ">=1.1.0", optional = true }
dm-control = { version = ">=1.0.10", optional = true }
h5py = { version = ">=3.7.0", optional = true }
optax = { version = "0.1.4", optional = true }
chex = { version = "0.1.5", optional = true }



#pytest = { version = "^7.1.3", optional = true }


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
atari = ["ale-py", "AutoROM", "opencv-python", "shimmy"]
procgen = ["procgen"]
plot = ["pandas", "seaborn"]
pytest = ["pytest"]
mujoco = ["mujoco", "imageio"]
jax = ["jax", "jaxlib", "flax"]
docs = ["mkdocs-material", "markdown-include", "openrlbenchmark"]
envpool = ["envpool"]
optuna = ["optuna", "optuna-dashboard"]
pettingzoo = ["PettingZoo", "SuperSuit", "multi-agent-ale-py"]
dm_control = ["shimmy", "mujoco", "dm-control", "h5py"]

# dependencies for algorithm variant (useful when you want to run a specific algorithm)
dqn = []
dqn_jax = ["jax", "jaxlib", "flax"]
c51 = []
c51_jax = ["jax", "jaxlib", "flax"]



