[tool.poetry]
name = "sep-groupb"
version = "0.1.0"
readme = "README.md"
authors = [
    "Malik Durmus <malikdurmus2@gmail.com>"
]
description = "Reinforcement Learning from Human Feedback Framework"
packages = [
    { include = "rlhf"}
]


[tool.poetry.dependencies]
python = ">=3.8,<3.11"
tensorboard = "^2.10.0"
wandb = "^0.13.11"
gym = "0.23.1"
torch = ">=1.12.1"
stable-baselines3 = "2.0.0"
gymnasium = ">=0.28.1"
moviepy = "^1.0.3"
tyro = "^0.5.10"
mujoco = "<=2.3.3"
numpy = ">=1.21.6"


#pytest = { version = "^7.1.3", optional = true }


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
pytest = ["pytest"]
mujoco = ["mujoco", "imageio"]